mod case_folding;
mod derived_core_properties;

fn main() {
    println!("/// DO NOT EDIT! This file is autogenerated from gen-unicode.\n");
    println!("use crate::unicode::{{CodePointRange, FoldRange}};");
    println!("{}", derived_core_properties::generate_id_start());
    println!("{}", derived_core_properties::generate_id_continue());
    println!("{}", case_folding::generate_folds());
}
